### ISSUE TITLE
大神 这个如果能够和mhinz/vim-startify配合使用就好了 

### ISSUE THREAD

**Issue by huayue369** [iamcco/clock.nvim#2]

**Comment by iamcco** [comment]
什么问题

**Comment by huayue369** [comment]
vim-startify不是可以在封面设置自己的文字显示吗  可不可以把你这个输出到它那个界面区  让自定义文字变成你这个大钟 简直完美

**Comment by iamcco** [comment]
这个不知道怎么搞，也不想搞，因为我不用 vim-startify

字体在这里，你可以自己研究下：
https://github.com/iamcco/clock.nvim/blob/master/rplugin/sran/clockn/src/fronts.ts
