### ISSUE TITLE
Can't set color

### ISSUE THREAD

**Issue by Leeshe** [iamcco/clock.nvim#3]
Version: 0.4

I can't set the clock's color in terminal:

```vim
" auto enable when neovim start
let g:clockn_enable = 1

" config the clock's color
let g:clockn_color = '#0066ff'

" position distance to top and right
let g:clockn_to_top = 33
let g:clockn_to_right = 1
```

Here is my config: https://github.com/Leeshe/myconfig/blob/master/init.vim

**Comment by iamcco** [comment]
Enable truecolor with `set termguicolors` or use `ClockNormal` highlight group.

**Comment by Leeshe** [comment]
Thanks, it works.
