### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by heguohui2018** [iamcco/clock.nvim#7]
能够成功安装但是，运行：ClockEnable命令报错，不知道怎么回事
<img width="672" alt="截屏2019-10-1300 13 33" src="https://user-images.githubusercontent.com/35359288/66704424-840a2480-ed4e-11e9-9f0b-594df9e87879.png">

重启也没有效果

**Comment by iamcco** [comment]
没装成功

**Comment by heguohui2018** [comment]
还有一个问题，在我安装后会影响到我重新映射的窗口跳转，
control+h向左跳转变成了增加当前窗口尺寸
control+l向右跳转变成了减小窗口的尺寸

**Comment by Dreamer-liuyang** [comment]
> 能够成功安装但是，运行：ClockEnable命令报错，不知道怎么回事
> <img alt="截屏2019-10-1300 13 33" width="672" src="https://user-images.githubusercontent.com/35359288/66704424-840a2480-ed4e-11e9-9f0b-594df9e87879.png">
> 
> 重启也没有效果

我也遇到了这个问题，请问你是怎么解决的呢？

**Comment by iamcco** [comment]
@Dreamer-liuyang 不知道你怎么安装的，插件没装成功

**Comment by Dreamer-liuyang** [comment]
> @Dreamer-liuyang 不知道你怎么安装的，插件没装成功

1. 首先把这两个拷贝进我的配置文件
```
Plug 'iamcco/sran.nvim', { 'do': { -> sran#util#install() } }
Plug 'iamcco/clock.nvim'                " 时钟
```
2. 然后退出重新进了一下，然后执行`:plugInstall`命令，然后有了下面的界面
![深度截图_选择区域_20200402194924](https://user-images.githubusercontent.com/46812648/78246114-301d1300-751b-11ea-84b8-9cc0f3dd35a7.png)
3. 然后进行配置
```
let g:clockn_enable = 1
highlight ClockNormal guifg=#000000
let g:clockn_to_top = 1
let g:clockn_to_right = 1
```
4. 最后运行：ClockEnable命令报错，不知道怎么回事

**Comment by iamcco** [comment]
肯定第一次装的时候 `:call sran#util#install()` 没装成功，重新执行下

**Comment by Dreamer-liuyang** [comment]
> call sran#util#install()

显示了这个
```[sran.nvim]: install completed```
但是运行`：ClockEnable`命令还是会显示`这不是编辑器的命令`

**Comment by iamcco** [comment]
什么系统和版本的vim

**Comment by Dreamer-liuyang** [comment]
我的系统是Manjaro，neovim版本是0.4.3，具体情况请看下图。

![image](https://user-images.githubusercontent.com/46812648/78250246-25b24780-7522-11ea-9c3a-06007817d6d0.png)

**Comment by iamcco** [comment]
`:echo sran#util#pre_build_version()` 输出什么

**Comment by Dreamer-liuyang** [comment]
什么也没有输出。

**Comment by iamcco** [comment]
预编译版本的你系统不能用

删了重装（需要nodejs支持，如果没有的话不用折腾了，自己用vimscirpt写一个也没多少代码）

```
Plug 'iamcco/sran.nvim', { 'do': 'yarn' }
```

或者如果你用 coc.nvim 的话安装 https://github.com/iamcco/coc-clock

**Comment by Dreamer-liuyang** [comment]
OK，我试试安装COC的
